package net.minecraft.src.eui.robotics;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
//Model code generated by MCModeller. All animation, AI,
//and special features are yours to program. Also keep in
//mind that some of these class names may have changed since
//wrote this. Make sure to check for compatibility with the
//latest version of the Minecraft Coder Pack before attempting
//to use this code.
import net.minecraft.src.ModelRenderer;

public class ModelModelShoeBot extends ModelBase
{
	public ModelRenderer body;
	public ModelRenderer Head;
	
	public ModelModelShoeBot()
	{
		body = new ModelRenderer(this,0, 0);
		body.addBox(-4.0F, -2.0F, -4.0F, 8, 4, 8, 0);
		
		Head = new ModelRenderer(this,0, 0);
		Head.addBox(-2.0F, -2.0F, -2.0F, 4, 4, 4, 0);
		
	}
	@Override
	 public void render(Entity par1Entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
		this.setRotationAngles(f, f1, f2, f3, f4, f5);
		body.render(f5);
		Head.render(f5);
	}
	private void setRotation(ModelRenderer model, float x, float y, float z)
	  {
	    model.rotateAngleX = x;
	    model.rotateAngleY = y;
	    model.rotateAngleZ = z;
	  }
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	  {
	    super.setRotationAngles(f, f1, f2, f3, f4, f5);
	  }
	
}
