// Date: 9/17/2013 12:00:07 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelGrinder extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer rightSide;
    ModelRenderer leftSide;
    ModelRenderer front;
    ModelRenderer back;
    ModelRenderer base;
    ModelRenderer uDisk1;
    ModelRenderer uDisk2;
    ModelRenderer uDisk3;
    ModelRenderer uDisk4;
    ModelRenderer uDisk5;
    ModelRenderer uDisk6;
    ModelRenderer dDisk1;
    ModelRenderer dDisk2;
    ModelRenderer dDisk3;
    ModelRenderer dDisk4;
    ModelRenderer dDisk5;
    ModelRenderer dDisk6;
  
  public ModelGrinder()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      base = new ModelRenderer(this, 1, 109);
      base.addBox(-8F, 0F, -8F, 16, 2, 16);
      base.setRotationPoint(0F, 22F, 0F);
      base.setTextureSize(128, 128);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      rightSide = new ModelRenderer(this, 0, 80);
      rightSide.addBox(0F, 0F, 0F, 2, 13, 13);
      rightSide.setRotationPoint(-8F, 9F, -6F);
      rightSide.setTextureSize(128, 128);
      rightSide.mirror = true;
      setRotation(rightSide, 0F, 0F, 0F);
      leftSide = new ModelRenderer(this, 40, 80);
      leftSide.addBox(0F, 0F, 0F, 2, 13, 13);
      leftSide.setRotationPoint(6F, 9F, -6F);
      leftSide.setTextureSize(128, 128);
      leftSide.mirror = true;
      setRotation(leftSide, 0F, 0F, 0F);
      front = new ModelRenderer(this, 78, 114);
      front.addBox(-8F, 0F, -8F, 16, 5, 2);
      front.setRotationPoint(0F, 17F, 0F);
      front.setTextureSize(128, 128);
      front.mirror = true;
      setRotation(front, 0F, 0F, 0F);
      back = new ModelRenderer(this, 78, 95);
      back.addBox(-8F, 0F, -3F, 16, 13, 1);
      back.setRotationPoint(0F, 9F, 10F);
      back.setTextureSize(128, 128);
      back.mirror = true;
      setRotation(back, 0F, 0F, 0F);
      base = new ModelRenderer(this, 1, 65);
      base.addBox(-8F, 0F, -8F, 14, 1, 10);
      base.setRotationPoint(1F, 8F, 5F);
      base.setTextureSize(128, 128);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      uDisk1 = new ModelRenderer(this, 0, 0);
      uDisk1.addBox(0F, -4F, -4F, 1, 8, 8);
      uDisk1.setRotationPoint(-6F, 14F, 1F);
      uDisk1.setTextureSize(128, 128);
      uDisk1.mirror = true;
      setRotation(uDisk1, 0.7853982F, 0F, 0F);
      uDisk2 = new ModelRenderer(this, 0, 0);
      uDisk2.addBox(0F, -4F, -4F, 1, 8, 8);
      uDisk2.setRotationPoint(-4F, 14F, 1F);
      uDisk2.setTextureSize(128, 128);
      uDisk2.mirror = true;
      setRotation(uDisk2, 0F, 0F, 0F);
      uDisk3 = new ModelRenderer(this, 0, 0);
      uDisk3.addBox(4F, -4F, -4F, 1, 8, 8);
      uDisk3.setRotationPoint(-6F, 14F, 1F);
      uDisk3.setTextureSize(128, 128);
      uDisk3.mirror = true;
      setRotation(uDisk3, 0.7853982F, 0F, 0F);
      uDisk4 = new ModelRenderer(this, 0, 0);
      uDisk4.addBox(6F, -4F, -4F, 1, 8, 8);
      uDisk4.setRotationPoint(-6F, 14F, 1F);
      uDisk4.setTextureSize(128, 128);
      uDisk4.mirror = true;
      setRotation(uDisk4, 0F, 0F, 0F);
      uDisk5 = new ModelRenderer(this, 0, 0);
      uDisk5.addBox(8F, -4F, -4F, 1, 8, 8);
      uDisk5.setRotationPoint(-6F, 14F, 1F);
      uDisk5.setTextureSize(128, 128);
      uDisk5.mirror = true;
      setRotation(uDisk5, 0.7853982F, 0F, 0F);
      uDisk6 = new ModelRenderer(this, 0, 0);
      uDisk6.addBox(10F, -4F, -4F, 1, 8, 8);
      uDisk6.setRotationPoint(-6F, 14F, 1F);
      uDisk6.setTextureSize(128, 128);
      uDisk6.mirror = true;
      setRotation(uDisk6, 0F, 0F, 0F);
      dDisk1 = new ModelRenderer(this, 0, 0);
      dDisk1.addBox(0F, -4F, -4F, 1, 8, 8);
      dDisk1.setRotationPoint(-5F, 17F, 0F);
      dDisk1.setTextureSize(128, 128);
      dDisk1.mirror = true;
      setRotation(dDisk1, 0F, 0F, 0F);
      dDisk2 = new ModelRenderer(this, 0, 0);
      dDisk2.addBox(2F, -4F, -4F, 1, 8, 8);
      dDisk2.setRotationPoint(-5F, 17F, 0F);
      dDisk2.setTextureSize(128, 128);
      dDisk2.mirror = true;
      setRotation(dDisk2, 0.7853982F, 0F, 0F);
      dDisk3 = new ModelRenderer(this, 0, 0);
      dDisk3.addBox(4F, -4F, -4F, 1, 8, 8);
      dDisk3.setRotationPoint(-5F, 17F, 0F);
      dDisk3.setTextureSize(128, 128);
      dDisk3.mirror = true;
      setRotation(dDisk3, 0F, 0F, 0F);
      dDisk4 = new ModelRenderer(this, 0, 0);
      dDisk4.addBox(6F, -4F, -4F, 1, 8, 8);
      dDisk4.setRotationPoint(-5F, 17F, 0F);
      dDisk4.setTextureSize(128, 128);
      dDisk4.mirror = true;
      setRotation(dDisk4, 0.7853982F, 0F, 0F);
      dDisk5 = new ModelRenderer(this, 0, 0);
      dDisk5.addBox(8F, -4F, -4F, 1, 8, 8);
      dDisk5.setRotationPoint(-5F, 17F, 0F);
      dDisk5.setTextureSize(128, 128);
      dDisk5.mirror = true;
      setRotation(dDisk5, 0F, 0F, 0F);
      dDisk6 = new ModelRenderer(this, 0, 0);
      dDisk6.addBox(10F, -4F, -4F, 1, 8, 8);
      dDisk6.setRotationPoint(-5F, 17F, 0F);
      dDisk6.setTextureSize(128, 128);
      dDisk6.mirror = true;
      setRotation(dDisk6, 0.7853982F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    base.render(f5);
    rightSide.render(f5);
    leftSide.render(f5);
    front.render(f5);
    back.render(f5);
    base.render(f5);
    uDisk1.render(f5);
    uDisk2.render(f5);
    uDisk3.render(f5);
    uDisk4.render(f5);
    uDisk5.render(f5);
    uDisk6.render(f5);
    dDisk1.render(f5);
    dDisk2.render(f5);
    dDisk3.render(f5);
    dDisk4.render(f5);
    dDisk5.render(f5);
    dDisk6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
