// Date: 11/27/2013 9:27:04 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.builtbroken.assemblyline.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelSmallFluidCan extends ModelBase
{
    //fields
    ModelRenderer body1;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer body4;
    ModelRenderer edge1;
    ModelRenderer edge2;
    ModelRenderer edge3;
    ModelRenderer edge4;
    ModelRenderer glass1;
    ModelRenderer glass2;
    ModelRenderer glass3;
    ModelRenderer glass4;

    public ModelSmallFluidCan()
    {
        textureWidth = 64;
        textureHeight = 32;

        body1 = new ModelRenderer(this, 12, 28);
        body1.addBox(-1.5F, 0F, -1.5F, 3, 1, 3);
        body1.setRotationPoint(0F, 23F, 0F);
        body1.setTextureSize(64, 32);
        body1.mirror = true;
        setRotation(body1, 0F, 0F, 0F);
        body2 = new ModelRenderer(this, 10, 22);
        body2.addBox(-2F, -1F, -2F, 4, 1, 4);
        body2.setRotationPoint(0F, 23F, 0F);
        body2.setTextureSize(64, 32);
        body2.mirror = true;
        setRotation(body2, 0F, 0F, 0F);
        body3 = new ModelRenderer(this, 10, 5);
        body3.addBox(-2F, -1F, -2F, 4, 1, 4);
        body3.setRotationPoint(0F, 17F, 0F);
        body3.setTextureSize(64, 32);
        body3.mirror = true;
        setRotation(body3, 0F, 0F, 0F);
        body4 = new ModelRenderer(this, 12, 0);
        body4.addBox(-1.5F, 0F, -1.5F, 3, 1, 3);
        body4.setRotationPoint(0F, 15F, 0F);
        body4.setTextureSize(64, 32);
        body4.mirror = true;
        setRotation(body4, 0F, 0F, 0F);
        edge1 = new ModelRenderer(this, 21, 13);
        edge1.addBox(-1.9F, -1F, -1.9F, 1, 5, 1);
        edge1.setRotationPoint(0F, 18F, 0F);
        edge1.setTextureSize(64, 32);
        edge1.mirror = true;
        setRotation(edge1, 0F, 0F, 0F);
        edge2 = new ModelRenderer(this, 26, 13);
        edge2.addBox(-2.1F, -1F, -1.9F, 1, 5, 1);
        edge2.setRotationPoint(3F, 18F, 0F);
        edge2.setTextureSize(64, 32);
        edge2.mirror = true;
        setRotation(edge2, 0F, 0F, 0F);
        edge3 = new ModelRenderer(this, 10, 13);
        edge3.addBox(-2.1F, -1F, 0.9F, 1, 5, 1);
        edge3.setRotationPoint(3F, 18F, 0F);
        edge3.setTextureSize(64, 32);
        edge3.mirror = true;
        setRotation(edge3, 0F, 0F, 0F);
        edge4 = new ModelRenderer(this, 16, 13);
        edge4.addBox(-1.9F, -1F, 0.9F, 1, 5, 1);
        edge4.setRotationPoint(0F, 18F, 0F);
        edge4.setTextureSize(64, 32);
        edge4.mirror = true;
        setRotation(edge4, 0F, 0F, 0F);
        glass1 = new ModelRenderer(this, 2, 13);
        glass1.addBox(-3.1F, -1F, 1.8F, 2, 5, 0);
        glass1.setRotationPoint(2F, 18F, 0F);
        glass1.setTextureSize(64, 32);
        glass1.mirror = true;
        setRotation(glass1, 0F, 0F, 0F);
        glass2 = new ModelRenderer(this, 2, 13);
        glass2.addBox(-3.1F, -1F, 0.2F, 2, 5, 0);
        glass2.setRotationPoint(2F, 18F, -2F);
        glass2.setTextureSize(64, 32);
        glass2.mirror = true;
        setRotation(glass2, 0F, 0F, 0F);
        glass3 = new ModelRenderer(this, 2, 13);
        glass3.addBox(-1.1F, -1F, -0.2F, 2, 5, 0);
        glass3.setRotationPoint(2F, 18F, 0F);
        glass3.setTextureSize(64, 32);
        glass3.mirror = true;
        setRotation(glass3, 0F, 1.570796F, 0F);
        glass4 = new ModelRenderer(this, 2, 13);
        glass4.addBox(-1.1F, -1F, 2.2F, 2, 5, 0);
        glass4.setRotationPoint(-4F, 18F, 0F);
        glass4.setTextureSize(64, 32);
        glass4.mirror = true;
        setRotation(glass4, 0F, 1.570796F, 0F);
    }

    public void render(float f5)
    {
        body1.render(f5);
        body2.render(f5);
        body3.render(f5);
        body4.render(f5);
        edge1.render(f5);
        edge2.render(f5);
        edge3.render(f5);
        edge4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
