// Date: 11/12/2013 5:48:04 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.builtbroken.assemblyline.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelMiningLaserGun extends ModelBase
{
    //fields
    ModelRenderer grip;
    ModelRenderer grip2;
    ModelRenderer body;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer body4;
    ModelRenderer body5;
    ModelRenderer body6;
    ModelRenderer barrel;
    ModelRenderer barrel2;
    ModelRenderer screen;
    ModelRenderer battery;
    ModelRenderer batteryClip;
    ModelRenderer batteryClip2;

    public ModelMiningLaserGun()
    {
        textureWidth = 128;
        textureHeight = 64;

        grip = new ModelRenderer(this, 1, 26);
        grip.addBox(0F, 0F, 0F, 1, 2, 1);
        grip.setRotationPoint(0.5F, 19F, -2F);
        grip.setTextureSize(128, 64);
        grip.mirror = true;
        setRotation(grip, 0.4014257F, 0F, 0F);
        grip2 = new ModelRenderer(this, 32, 2);
        grip2.addBox(-1.5F, 0F, 0F, 3, 1, 1);
        grip2.setRotationPoint(4.5F, 17.58F, -12.01F);
        grip2.setTextureSize(128, 64);
        grip2.mirror = true;
        setRotation(grip2, 0F, 0F, 0F);
        body = new ModelRenderer(this, 16, 39);
        body.addBox(-1.5F, 0F, 0F, 3, 3, 13);
        body.setRotationPoint(1F, 15.8F, -11.01F);
        body.setTextureSize(128, 64);
        body.mirror = true;
        setRotation(body, 0F, 0F, 0F);
        body2 = new ModelRenderer(this, 49, 41);
        body2.addBox(0F, 0F, 0F, 2, 1, 13);
        body2.setRotationPoint(0F, 15.6F, -11.01F);
        body2.setTextureSize(128, 64);
        body2.mirror = true;
        setRotation(body2, 0F, 0F, 0F);
        body3 = new ModelRenderer(this, 55, 7);
        body3.addBox(-1.5F, 0F, 0F, 2, 1, 8);
        body3.setRotationPoint(1.5F, 18.8F, -15.01F);
        body3.setTextureSize(128, 64);
        body3.mirror = true;
        setRotation(body3, 0F, 0F, 0F);
        body4 = new ModelRenderer(this, 0, 0);
        body4.addBox(0F, 0F, 0F, 2, 1, 5);
        body4.setRotationPoint(0F, 18F, -3F);
        body4.setTextureSize(128, 64);
        body4.mirror = true;
        setRotation(body4, 0F, 0F, 0F);
        body5 = new ModelRenderer(this, 17, 7);
        body5.addBox(-1.5F, 0F, 0F, 1, 2, 8);
        body5.setRotationPoint(0.5F, 17F, -15.01F);
        body5.setTextureSize(128, 64);
        body5.mirror = true;
        setRotation(body5, 0F, 0F, 0F);
        body6 = new ModelRenderer(this, 36, 7);
        body6.addBox(-1.5F, 0F, 0F, 1, 2, 8);
        body6.setRotationPoint(3.5F, 17F, -15.01F);
        body6.setTextureSize(128, 64);
        body6.mirror = true;
        setRotation(body6, 0F, 0F, 0F);
        barrel = new ModelRenderer(this, 34, 21);
        barrel.addBox(0F, 0F, 0F, 1, 3, 8);
        barrel.setRotationPoint(0.5F, 16F, -19.01F);
        barrel.setTextureSize(128, 64);
        barrel.mirror = true;
        setRotation(barrel, 0F, 0F, 0F);
        barrel2 = new ModelRenderer(this, 55, 23);
        barrel2.addBox(0F, 0F, 0F, 2, 2, 6);
        barrel2.setRotationPoint(0F, 16.8F, -17.01F);
        barrel2.setTextureSize(128, 64);
        barrel2.mirror = true;
        setRotation(barrel2, 0F, 0F, 0F);
        screen = new ModelRenderer(this, 7, 10);
        screen.addBox(0F, 0F, 0F, 3, 3, 1);
        screen.setRotationPoint(2.5F, 16F, -8.01F);
        screen.setTextureSize(128, 64);
        screen.mirror = true;
        setRotation(screen, 0.5410521F, 0F, 0F);
        battery = new ModelRenderer(this, 17, 22);
        battery.addBox(-1.5F, 0F, 0F, 2, 4, 5);
        battery.setRotationPoint(-1F, 16F, -6.5F);
        battery.setTextureSize(128, 64);
        battery.mirror = true;
        setRotation(battery, 0F, 0F, 0F);
        batteryClip = new ModelRenderer(this, 17, 0);
        batteryClip.addBox(-1.5F, 0F, 0F, 2, 1, 1);
        batteryClip.setRotationPoint(-0.4F, 16.5F, -2F);
        batteryClip.setTextureSize(128, 64);
        batteryClip.mirror = true;
        setRotation(batteryClip, 0F, 0F, 0F);
        batteryClip2 = new ModelRenderer(this, 17, 0);
        batteryClip2.addBox(-1.5F, 0F, 0F, 2, 1, 1);
        batteryClip2.setRotationPoint(-0.4F, 16.5F, -7F);
        batteryClip2.setTextureSize(128, 64);
        batteryClip2.mirror = true;
        setRotation(batteryClip2, 0F, 0F, 0F);
    }

    public void render(float f5)
    {
        grip.render(f5);
        grip2.render(f5);
        body.render(f5);
        body2.render(f5);
        body3.render(f5);
        body4.render(f5);
        body5.render(f5);
        body6.render(f5);
        barrel.render(f5);
        barrel2.render(f5);
        screen.render(f5);
        battery.render(f5);
        batteryClip.render(f5);
        batteryClip2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
