// Date: 11/12/2013 5:27:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.builtbroken.assemblyline.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelLaserTile extends ModelBase
{
    //fields
    ModelRenderer base;
    ModelRenderer base2;
    ModelRenderer rod;
    ModelRenderer body;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer body4;
    ModelRenderer body5;
    ModelRenderer body6;
    ModelRenderer body7;

    public ModelLaserTile()
    {
        textureWidth = 128;
        textureHeight = 128;

        base = new ModelRenderer(this, 0, 76);
        base.addBox(-5F, 0F, -5F, 10, 1, 10);
        base.setRotationPoint(0F, 23F, 0F);
        base.setTextureSize(128, 128);
        base.mirror = true;
        setRotation(base, 0F, 0F, 0F);
        base2 = new ModelRenderer(this, 0, 66);
        base2.addBox(-4F, 0F, -4F, 8, 1, 8);
        base2.setRotationPoint(0F, 22F, 0F);
        base2.setTextureSize(128, 128);
        base2.mirror = true;
        setRotation(base2, 0F, 0F, 0F);
        rod = new ModelRenderer(this, 0, 53);
        rod.addBox(-1.5F, -1F, -1.5F, 3, 8, 3);
        rod.setRotationPoint(0F, 15F, 0F);
        rod.setTextureSize(128, 128);
        rod.mirror = true;
        setRotation(rod, 0F, 0F, 0F);
        body = new ModelRenderer(this, 0, 35);
        body.addBox(-3.5F, -1F, -2.5F, 9, 3, 5);
        body.setRotationPoint(0F, 10F, 0F);
        body.setTextureSize(128, 128);
        body.mirror = true;
        setRotation(body, 0F, 0F, 0F);
        body2 = new ModelRenderer(this, 0, 44);
        body2.addBox(-3.5F, -1F, -2F, 7, 2, 4);
        body2.setRotationPoint(0F, 13F, 0F);
        body2.setTextureSize(128, 128);
        body2.mirror = true;
        setRotation(body2, 0F, 0F, 0F);
        body3 = new ModelRenderer(this, 30, 37);
        body3.addBox(-3.5F, -1F, -2F, 3, 4, 4);
        body3.setRotationPoint(-3F, 10.3F, 0F);
        body3.setTextureSize(128, 128);
        body3.mirror = true;
        setRotation(body3, 0F, 0F, 0F);
        body4 = new ModelRenderer(this, 57, 34);
        body4.addBox(-3.5F, -1.5F, -1F, 3, 1, 2);
        body4.setRotationPoint(-6F, 11F, 0F);
        body4.setTextureSize(128, 128);
        body4.mirror = true;
        setRotation(body4, 0F, 0F, 0F);
        body5 = new ModelRenderer(this, 57, 47);
        body5.addBox(-3.5F, -1.5F, -1F, 3, 1, 2);
        body5.setRotationPoint(-6F, 13F, 0F);
        body5.setTextureSize(128, 128);
        body5.mirror = true;
        setRotation(body5, 0F, 0F, 0F);
        body6 = new ModelRenderer(this, 66, 42);
        body6.addBox(-3.5F, -1.5F, -1.5F, 3, 1, 1);
        body6.setRotationPoint(-6F, 12F, 0F);
        body6.setTextureSize(128, 128);
        body6.mirror = true;
        setRotation(body6, 0F, 0F, 0F);
        body7 = new ModelRenderer(this, 51, 41);
        body7.addBox(-3.5F, -1.5F, 0.5F, 3, 1, 1);
        body7.setRotationPoint(-6F, 12F, 0F);
        body7.setTextureSize(128, 128);
        body7.mirror = true;
        setRotation(body7, 0F, 0F, 0F);
    }

    public void render(float f5)
    {
        base.render(f5);
        base2.render(f5);
        rod.render(f5);
        body.render(f5);
        body2.render(f5);
        body3.render(f5);
        body4.render(f5);
        body5.render(f5);
        body6.render(f5);
        body7.render(f5);
    }

    public void renderAll()
    {
        this.render(0.0625F);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
