// Date: 11/27/2013 5:36:07 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.builtbroken.assemblyline.client.model;

import net.minecraft.client.model.ModelRenderer;

public class ModelSteamGen extends ModelMachine
{
    //fields
    ModelRenderer face;
    ModelRenderer grill;
    ModelRenderer grill2;
    ModelRenderer grill3;
    ModelRenderer grill4;
    ModelRenderer grill5;
    ModelRenderer grill6;
    ModelRenderer grill7;
    ModelRenderer grill8;
    ModelRenderer grill9;
    ModelRenderer grill10;
    ModelRenderer grill11;
    ModelRenderer grill12;
    ModelRenderer grill13;
    ModelRenderer grill14;
    ModelRenderer grill15;
    ModelRenderer grill16;
    ModelRenderer grill17;
    ModelRenderer tank;
    ModelRenderer tank2;
    ModelRenderer tank3;
    ModelRenderer tank4;
    ModelRenderer tank5;
    ModelRenderer tankTop;
    ModelRenderer tankTop2;
    ModelRenderer tankTop3;
    ModelRenderer tankTop4;
    ModelRenderer pipe;
    ModelRenderer pipe2;
    ModelRenderer gauge;
    ModelRenderer gaugeNeedle;

    public ModelSteamGen()
    {
        textureWidth = 128;
        textureHeight = 128;

        face = new ModelRenderer(this, 20, 93);
        face.addBox(-8F, 0F, -6F, 16, 6, 14);
        face.setRotationPoint(0F, 18F, 0F);
        face.setTextureSize(128, 128);
        face.mirror = true;
        setRotation(face, 0F, 0F, 0F);
        grill = new ModelRenderer(this, 44, 56);
        grill.addBox(0F, 0F, 0F, 1, 5, 1);
        grill.setRotationPoint(-7.6F, 18.5F, -7F);
        grill.setTextureSize(128, 128);
        grill.mirror = true;
        setRotation(grill, 0F, 0F, 0F);
        grill2 = new ModelRenderer(this, 38, 56);
        grill2.addBox(0F, 0F, 0F, 1, 5, 1);
        grill2.setRotationPoint(6.4F, 18.5F, -7F);
        grill2.setTextureSize(128, 128);
        grill2.mirror = true;
        setRotation(grill2, 0F, 0F, 0F);
        grill3 = new ModelRenderer(this, 0, 49);
        grill3.addBox(0F, 0F, 0F, 13, 1, 1);
        grill3.setRotationPoint(-6.6F, 18.5F, -7F);
        grill3.setTextureSize(128, 128);
        grill3.mirror = true;
        setRotation(grill3, 0F, 0F, 0F);
        grill4 = new ModelRenderer(this, 0, 52);
        grill4.addBox(0F, 0F, 0F, 13, 1, 1);
        grill4.setRotationPoint(-6.6F, 22.5F, -7F);
        grill4.setTextureSize(128, 128);
        grill4.mirror = true;
        setRotation(grill4, 0F, 0F, 0F);
        grill5 = new ModelRenderer(this, 0, 56);
        grill5.addBox(0F, 0F, 0F, 1, 3, 1);
        grill5.setRotationPoint(-6.6F, 19.5F, -6F);
        grill5.setTextureSize(128, 128);
        grill5.mirror = true;
        setRotation(grill5, 0F, 0.7853982F, 0F);
        grill6 = new ModelRenderer(this, 0, 56);
        grill6.addBox(0F, 0F, 0F, 1, 3, 1);
        grill6.setRotationPoint(5F, 19.5F, -6F);
        grill6.setTextureSize(128, 128);
        grill6.mirror = true;
        setRotation(grill6, 0F, 0.7853982F, 0F);
        grill7 = new ModelRenderer(this, 0, 56);
        grill7.addBox(0F, 0F, 0F, 1, 3, 1);
        grill7.setRotationPoint(4F, 19.5F, -6F);
        grill7.setTextureSize(128, 128);
        grill7.mirror = true;
        setRotation(grill7, 0F, 0.7853982F, 0F);
        grill8 = new ModelRenderer(this, 0, 56);
        grill8.addBox(0F, 0F, 0F, 1, 3, 1);
        grill8.setRotationPoint(3F, 19.5F, -6F);
        grill8.setTextureSize(128, 128);
        grill8.mirror = true;
        setRotation(grill8, 0F, 0.7853982F, 0F);
        grill9 = new ModelRenderer(this, 0, 56);
        grill9.addBox(0F, 0F, 0F, 1, 3, 1);
        grill9.setRotationPoint(2F, 19.5F, -6F);
        grill9.setTextureSize(128, 128);
        grill9.mirror = true;
        setRotation(grill9, 0F, 0.7853982F, 0F);
        grill10 = new ModelRenderer(this, 0, 56);
        grill10.addBox(0F, 0F, 0F, 1, 3, 1);
        grill10.setRotationPoint(-5.6F, 19.5F, -6F);
        grill10.setTextureSize(128, 128);
        grill10.mirror = true;
        setRotation(grill10, 0F, 0.7853982F, 0F);
        grill11 = new ModelRenderer(this, 0, 56);
        grill11.addBox(0F, 0F, 0F, 1, 3, 1);
        grill11.setRotationPoint(-4.6F, 19.5F, -6F);
        grill11.setTextureSize(128, 128);
        grill11.mirror = true;
        setRotation(grill11, 0F, 0.7853982F, 0F);
        grill12 = new ModelRenderer(this, 0, 56);
        grill12.addBox(0F, 0F, 0F, 1, 3, 1);
        grill12.setRotationPoint(-3.6F, 19.5F, -6F);
        grill12.setTextureSize(128, 128);
        grill12.mirror = true;
        setRotation(grill12, 0F, 0.7853982F, 0F);
        grill13 = new ModelRenderer(this, 0, 56);
        grill13.addBox(0F, 0F, 0F, 1, 3, 1);
        grill13.setRotationPoint(-2.6F, 19.5F, -6F);
        grill13.setTextureSize(128, 128);
        grill13.mirror = true;
        setRotation(grill13, 0F, 0.7853982F, 0F);
        grill14 = new ModelRenderer(this, 0, 56);
        grill14.addBox(0F, 0F, 0F, 1, 3, 1);
        grill14.setRotationPoint(-1.6F, 19.5F, -6F);
        grill14.setTextureSize(128, 128);
        grill14.mirror = true;
        setRotation(grill14, 0F, 0.7853982F, 0F);
        grill15 = new ModelRenderer(this, 0, 56);
        grill15.addBox(0F, 0F, 0F, 1, 3, 1);
        grill15.setRotationPoint(1F, 19.5F, -6F);
        grill15.setTextureSize(128, 128);
        grill15.mirror = true;
        setRotation(grill15, 0F, 0.7853982F, 0F);
        grill16 = new ModelRenderer(this, 0, 56);
        grill16.addBox(0F, 0F, 0F, 1, 3, 1);
        grill16.setRotationPoint(0F, 19.5F, -6F);
        grill16.setTextureSize(128, 128);
        grill16.mirror = true;
        setRotation(grill16, 0F, 0.7853982F, 0F);
        grill17 = new ModelRenderer(this, 0, 56);
        grill17.addBox(0F, 0F, 0F, 1, 3, 1);
        grill17.setRotationPoint(-0.8F, 19.5F, -6F);
        grill17.setTextureSize(128, 128);
        grill17.mirror = true;
        setRotation(grill17, 0F, 0.7853982F, 0F);
        tank = new ModelRenderer(this, 22, 65);
        tank.addBox(-5F, 0F, -5F, 10, 8, 10);
        tank.setRotationPoint(0F, 10F, 2F);
        tank.setTextureSize(128, 128);
        tank.mirror = true;
        setRotation(tank, 0F, 0F, 0F);
        tank2 = new ModelRenderer(this, 0, 66);
        tank2.addBox(-4F, 0F, -6F, 8, 8, 1);
        tank2.setRotationPoint(0F, 10F, 2F);
        tank2.setTextureSize(128, 128);
        tank2.mirror = true;
        setRotation(tank2, 0F, 0F, 0F);
        tank3 = new ModelRenderer(this, 0, 65);
        tank3.addBox(-4F, 0F, -6F, 8, 8, 1);
        tank3.setRotationPoint(0F, 10F, 2F);
        tank3.setTextureSize(128, 128);
        tank3.mirror = true;
        setRotation(tank3, 0F, 1.570796F, 0F);
        tank4 = new ModelRenderer(this, 0, 65);
        tank4.addBox(-4F, 0F, -6F, 8, 8, 1);
        tank4.setRotationPoint(0F, 10F, 2F);
        tank4.setTextureSize(128, 128);
        tank4.mirror = true;
        setRotation(tank4, 0F, 3.141593F, 0F);
        tank5 = new ModelRenderer(this, 0, 65);
        tank5.addBox(-4F, 0F, -6F, 8, 8, 1);
        tank5.setRotationPoint(0F, 10F, 2F);
        tank5.setTextureSize(128, 128);
        tank5.mirror = true;
        setRotation(tank5, 0F, -1.570796F, 0F);
        tankTop = new ModelRenderer(this, 0, 11);
        tankTop.addBox(0F, 0F, 0F, 16, 2, 4);
        tankTop.setRotationPoint(-8F, 8F, -6F);
        tankTop.setTextureSize(128, 128);
        tankTop.mirror = true;
        setRotation(tankTop, 0F, 0F, 0F);
        tankTop2 = new ModelRenderer(this, 0, 18);
        tankTop2.addBox(-4F, 0F, 2F, 8, 2, 4);
        tankTop2.setRotationPoint(0F, 8F, 2F);
        tankTop2.setTextureSize(128, 128);
        tankTop2.mirror = true;
        setRotation(tankTop2, 0F, 0F, 0F);
        tankTop3 = new ModelRenderer(this, 29, 25);
        tankTop3.addBox(0F, 0F, 0F, 4, 2, 10);
        tankTop3.setRotationPoint(4F, 8F, -2F);
        tankTop3.setTextureSize(128, 128);
        tankTop3.mirror = true;
        setRotation(tankTop3, 0F, 0F, 0F);
        tankTop4 = new ModelRenderer(this, 0, 25);
        tankTop4.addBox(0F, 0F, 0F, 4, 2, 10);
        tankTop4.setRotationPoint(-8F, 8F, -2F);
        tankTop4.setTextureSize(128, 128);
        tankTop4.mirror = true;
        setRotation(tankTop4, 0F, 0F, 0F);
        pipe = new ModelRenderer(this, 10, 0);
        pipe.addBox(0F, 0F, 0F, 2, 8, 2);
        pipe.setRotationPoint(-7F, 10F, -5F);
        pipe.setTextureSize(128, 128);
        pipe.mirror = true;
        setRotation(pipe, 0F, 0F, 0F);
        pipe2 = new ModelRenderer(this, 0, 0);
        pipe2.addBox(0F, 0F, 0F, 2, 8, 2);
        pipe2.setRotationPoint(5F, 10F, -5F);
        pipe2.setTextureSize(128, 128);
        pipe2.mirror = true;
        setRotation(pipe2, 0F, 0F, 0F);
        gauge = new ModelRenderer(this, 59, 25);
        gauge.addBox(0F, 0F, 0F, 4, 4, 1);
        gauge.setRotationPoint(-2F, 12F, -4.5F);
        gauge.setTextureSize(128, 128);
        gauge.mirror = true;
        setRotation(gauge, 0F, 0F, 0F);
        gaugeNeedle = new ModelRenderer(this, 71, 25);
        gaugeNeedle.addBox(-0.5F, -2F, -1F, 1, 3, 0);
        gaugeNeedle.setRotationPoint(0F, 15F, -3.6F);
        gaugeNeedle.setTextureSize(128, 128);
        gaugeNeedle.mirror = true;
        setRotation(gaugeNeedle, -0.0174533F, 0F, -0.5759587F);
    }

    @Override
    public void render(float f5)
    {
        face.render(f5);
        grill.render(f5);
        grill2.render(f5);
        grill3.render(f5);
        grill4.render(f5);
        grill5.render(f5);
        grill6.render(f5);
        grill7.render(f5);
        grill8.render(f5);
        grill9.render(f5);
        grill10.render(f5);
        grill11.render(f5);
        grill12.render(f5);
        grill13.render(f5);
        grill14.render(f5);
        grill15.render(f5);
        grill16.render(f5);
        grill17.render(f5);
        tank.render(f5);
        tank2.render(f5);
        tank3.render(f5);
        tank4.render(f5);
        tank5.render(f5);
        tankTop.render(f5);
        tankTop2.render(f5);
        tankTop3.render(f5);
        tankTop4.render(f5);
        pipe.render(f5);
        pipe2.render(f5);
        gauge.render(f5);

    }

    public void renderGauge(float f5, float angle)
    {
        gaugeNeedle.rotateAngleZ = angle;
        gaugeNeedle.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
