// Date: 9/21/2013 11:03:18 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.builtbroken.assemblyline.client.model;

import net.minecraft.client.model.ModelRenderer;

public class ModelElecFurnace extends ModelMachine
{
    //fields
    ModelRenderer body;
    ModelRenderer top;
    ModelRenderer bot;
    ModelRenderer door;
    ModelRenderer tube1;
    ModelRenderer tube2;
    ModelRenderer tube3;

    public ModelElecFurnace()
    {
        textureWidth = 128;
        textureHeight = 128;

        body = new ModelRenderer(this, 0, 25);
        body.addBox(-7.5F, 0F, -7.5F, 15, 12, 10);
        body.setRotationPoint(0F, 10F, 1F);
        body.setTextureSize(128, 128);
        body.mirror = true;
        setRotation(body, 0F, 0F, 0F);
        top = new ModelRenderer(this, 0, 0);
        top.addBox(-8F, 0F, -8F, 16, 2, 15);
        top.setRotationPoint(0F, 8F, 1F);
        top.setTextureSize(128, 128);
        top.mirror = true;
        setRotation(top, 0F, 0F, 0F);
        bot = new ModelRenderer(this, 0, 56);
        bot.addBox(-8F, 0F, -8F, 16, 2, 15);
        bot.setRotationPoint(0F, 22F, 1F);
        bot.setTextureSize(128, 128);
        bot.mirror = true;
        setRotation(bot, 0F, 0F, 0F);
        door = new ModelRenderer(this, 0, 81);
        door.addBox(-6F, 1F, -8.5F, 12, 10, 1);
        door.setRotationPoint(0F, 10F, 1F);
        door.setTextureSize(128, 128);
        door.mirror = true;
        setRotation(door, 0F, 0F, 0F);
        tube1 = new ModelRenderer(this, 0, 99);
        tube1.addBox(-7.5F, 0F, -7.5F, 3, 12, 4);
        tube1.setRotationPoint(1F, 10F, 11F);
        tube1.setTextureSize(128, 128);
        tube1.mirror = true;
        setRotation(tube1, 0F, 0F, 0F);
        tube2 = new ModelRenderer(this, 34, 99);
        tube2.addBox(-7.5F, 0F, -7.5F, 3, 12, 4);
        tube2.setRotationPoint(11F, 10F, 11F);
        tube2.setTextureSize(128, 128);
        tube2.mirror = true;
        setRotation(tube2, 0F, 0F, 0F);
        tube3 = new ModelRenderer(this, 15, 99);
        tube3.addBox(-7.5F, 0F, -7.5F, 5, 12, 4);
        tube3.setRotationPoint(5F, 10F, 11F);
        tube3.setTextureSize(128, 128);
        tube3.mirror = true;
        setRotation(tube3, 0F, 0F, 0F);
    }

    @Override
    public void render(float f5)
    {
        body.render(f5);
        top.render(f5);
        bot.render(f5);
        door.render(f5);
        tube1.render(f5);
        tube2.render(f5);
        tube3.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
