// Date: 8/14/2012 1:48:41 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package SteamPower;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelCenterTank extends ModelBase
{
  
    ModelRenderer Block;
  
  public ModelCenterTank(float par1)
  {
    textureWidth = 128;
    textureHeight = 128;
    
      
      //block
      Block = new ModelRenderer(this, 0, 0);
      Block.addBox(0F, 0F, 0F, 16, 16, 16);
      Block.setRotationPoint(-8F, 8F, -8F);
      Block.setTextureSize(128, 32);
      Block.mirror = true;
      setRotation(Block, 0F, 0F, 0F);
  }
  public void renderBlock(float f5)
  {
	  Block.render(f5);
  }
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
